export const HTTP_STATUS = {
    SUCCESS: 200,
    CREATED: 201,
    UNAUTHORIZED: 401,
    INTERNAL_SERVER_ERROR: 500,
    BAD_INPUT: 400,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NO_CONTENT: 204,
    GONE: 410
};


export const SORT_ORDER = {
    ASC: 'ASC',
    DESC: 'DESC'
};